import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { validateList, codepointId } from './validate-list.mjs';
import { samplePath } from './sample-path.mjs';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const MEDIAN_POINTS = 8;

// Extract stroke path `d` strings from a KanjiVG SVG, ordered by stroke number.
export function extractStrokes(svg) {
  const re = /<path[^>]*\bid="kvg:[0-9a-f]+-s(\d+)"[^>]*\bd="([^"]+)"/g;
  const found = [];
  let m;
  while ((m = re.exec(svg)) !== null) {
    found.push({ n: Number(m[1]), d: m[2] });
  }
  found.sort((a, b) => a.n - b.n);
  return found.map((s) => s.d);
}

async function main() {
  const list = JSON.parse(await readFile(here('kanji-list.json'), 'utf8'));

  const { ok, errors } = validateList(list);
  if (!ok) {
    console.error('kanji-list.json validation failed:');
    for (const e of errors) console.error('  - ' + e);
    process.exit(1);
  }

  const out = [];
  for (const entry of list) {
    const svg = await readFile(here(`kanjivg-src/${entry.id}.svg`), 'utf8');
    const strokes = extractStrokes(svg);

    // Validation: stroke count must match the expected count in the list.
    if (strokes.length !== entry.strokeCount) {
      console.error(
        `[${entry.kanji}] stroke count mismatch: SVG has ${strokes.length}, expected ${entry.strokeCount}`
      );
      process.exit(1);
    }
    if (codepointId(entry.kanji) !== entry.id) {
      console.error(`[${entry.kanji}] id/codepoint mismatch`);
      process.exit(1);
    }

    const medians = strokes.map((d) => samplePath(d, MEDIAN_POINTS));

    out.push({
      id: entry.id,
      kanji: entry.kanji,
      grade: entry.grade,
      reading: entry.reading,
      sentence: entry.sentence,
      strokes,
      medians,
    });
  }

  const banner =
    '// AUTO-GENERATED by tools/convert-kanjivg.mjs — do not edit by hand.\n' +
    '// Stroke data derived from KanjiVG (Ulrich Apel), CC BY-SA 3.0. See ../LICENSE-DATA.\n';
  const body = 'export const KANJI_DATA = ' + JSON.stringify(out, null, 0) + ';\n';
  await writeFile(here('../data/kanji-data.js'), banner + body, 'utf8');
  console.log(`Wrote data/kanji-data.js (${out.length} kanji).`);
}

// Only run when executed directly (so tests can import extractStrokes).
if (process.argv[1] === here('convert-kanjivg.mjs')) {
  await main();
}
